name: Deploy to GitHub Pages

on:
  # Uruchamia się przy każdym pushu do gałęzi main
  push:
    branches: [ main ]
  # Pozwala na ręczne uruchomienie z zakładki Actions
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install, build, and upload your site
        uses: withastro/action@v0

      # Krok deployowania używając GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          # Następna linia jest ważna dla custom domain
          cname: eu.zentala.io